services:
  database:
    container_name: database
    image: postgres:17.5-alpine3.22
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  api_1: &api
    container_name: api_1
    build: .
    ports:
      - "3001:3000"
    env_file:
      - .env
    environment:
      RUN_DB_SETUP: true
    depends_on:
      - database

  api_2:
    <<: *api
    container_name: api_2
    ports:
      - "3002:3000"
    environment:
      RUN_DB_SETUP: false

  load_balancer:
    image: nginx:1.29.0-alpine3.22
    container_name: load_balancer
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "3000:3000"
    depends_on:
      - api_1
      - api_2