services:
  database:
    image: postgres:17.5-alpine3.22
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  api: &api
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - database