name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types: ["completed"]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Set up Keys
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-host: ${{ secrets.REMOTE_HOST }}

      - name: Deploy
        run: |
          sudo yum update -y
          sudo amazon-linux-extras install docker -y
          sudo service docker start
          sudo usermod -a -G docker $USER
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s ...)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

          # Git clone ou pull
          if [ -d app ]; then
            cd app && git reset --hard && git pull origin main
          else
            git clone github.com/alvesluis0/${{ github.repository }} app && cd app
          fi

          docker-compose pull || true
          docker-compose up -d --build